# Generated by Django 6.0.1 on 2026-01-26 23:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao_doenca', models.CharField(max_length=200, verbose_name='Previne que doença')),
                ('idade_alvo_meses', models.IntegerField(help_text='0 para ao nascer', verbose_name='Idade Alvo (meses)')),
                ('dose_padrao', models.CharField(default='Dose Única', max_length=50, verbose_name='Dose Padrão')),
            ],
            options={
                'ordering': ['idade_alvo_meses', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioACS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cnes_unidade', models.CharField(blank=True, max_length=20, verbose_name='CNES da Unidade')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Agente Comunitário de Saúde',
                'verbose_name_plural': 'Agentes Comunitários de Saúde',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cns', models.CharField(max_length=15, unique=True, verbose_name='CNS')),
                ('localidade', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=200, verbose_name='Nome da Mãe')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Em Aberto'), ('ATRASADA', 'Atrasada'), ('APLICADA', 'Aplicada')], default='PENDENTE', max_length=20)),
                ('dose', models.CharField(max_length=50)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('profissional_aplicou', models.CharField(blank=True, max_length=100)),
                ('data_aplicacao', models.DateField(blank=True, null=True)),
                ('via_administracao', models.CharField(blank=True, choices=[('INTRAMUSCULAR', 'Intramuscular'), ('SUBCUTANEA', 'Subcutânea'), ('ORAL', 'Oral'), ('INTRADERMICA', 'Intradérmica')], max_length=30)),
                ('local_aplicacao', models.CharField(blank=True, max_length=100)),
                ('estrategia', models.CharField(default='Rotina', max_length=100)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='core.crianca')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vacina')),
            ],
        ),
    ]
