# Generated by Django 6.0.1 on 2026-01-27 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovacina',
            name='crianca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.crianca'),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacina'),
        ),
    ]
