# Generated by Django 6.0.1 on 2026-01-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registrovacina_crianca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crianca',
            options={'ordering': ['nome']},
        ),
        migrations.AddIndex(
            model_name='crianca',
            index=models.Index(fields=['nome'], name='core_crianc_nome_c59da5_idx'),
        ),
        migrations.AddIndex(
            model_name='crianca',
            index=models.Index(fields=['data_nascimento'], name='core_crianc_data_na_000571_idx'),
        ),
        migrations.AddIndex(
            model_name='crianca',
            index=models.Index(fields=['sexo'], name='core_crianc_sexo_c84bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='crianca',
            index=models.Index(fields=['cns'], name='core_crianc_cns_95e624_idx'),
        ),
        migrations.AddIndex(
            model_name='registrovacina',
            index=models.Index(fields=['status'], name='core_regist_status_731510_idx'),
        ),
    ]
