# Generated by Django 6.0.1 on 2026-01-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_crianca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovacina',
            name='aplicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacinas_aplicadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
