# Generated by Django 6.0.1 on 2026-01-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registrovacina_aplicado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovacina',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
