# Generated by Django 6.0.1 on 2026-01-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registrovacina_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovacina',
            name='estrategia',
            field=models.CharField(choices=[('ROTINA', 'Rotina'), ('CAMPANHA', 'Campanha'), ('BLOQUEIO', 'Bloqueio'), ('ESPECIAL', 'Especial')], default='ROTINA', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='fabricante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='local_aplicacao',
            field=models.CharField(blank=True, choices=[('VASTO_LATERAL_D', 'Vasto Lateral Direito (Coxa)'), ('VASTO_LATERAL_E', 'Vasto Lateral Esquerdo (Coxa)'), ('DELTOIDE_D', 'Deltoide Direito (Braço)'), ('DELTOIDE_E', 'Deltoide Esquerdo (Braço)'), ('GLUTEO_D', 'Glúteo Direito'), ('GLUTEO_E', 'Glúteo Esquerdo'), ('BOCA', 'Boca (Oral)'), ('OUTROS', 'Outros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='profissional_aplicou',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='via_administracao',
            field=models.CharField(choices=[('INTRAMUSCULAR', 'Intramuscular'), ('ORAL', 'Oral'), ('SUBCUTANEA', 'Subcutânea'), ('INTRADERMICA', 'Intradérmica')], default='INTRAMUSCULAR', max_length=20),
        ),
    ]
