# Generated by Django 6.0.1 on 2026-01-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_registrovacina_estrategia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=100)),
                ('quantidade_disponivel', models.IntegerField(default=0)),
                ('validade', models.DateField(blank=True, null=True)),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.vacina')),
            ],
            options={
                'verbose_name': 'Lote Disponível',
                'verbose_name_plural': 'Lotes Disponíveis',
            },
        ),
    ]
