# Generated by Django 6.0.1 on 2026-02-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lotevacina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovacina',
            name='observacao',
        ),
        migrations.AlterField(
            model_name='crianca',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='dose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='estrategia',
            field=models.CharField(choices=[('Rotina', 'Rotina'), ('Campanha', 'Campanha'), ('Bloqueio', 'Bloqueio'), ('Especial', 'Especial')], default='Rotina', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='local_aplicacao',
            field=models.CharField(blank=True, choices=[('Deltoide Direito (Braço)', 'Deltoide Direito (Braço)'), ('Deltoide Esquerdo (Braço)', 'Deltoide Esquerdo (Braço)'), ('Vasto Lateral da Coxa D', 'Vasto Lateral da Coxa D'), ('Vasto Lateral da Coxa E', 'Vasto Lateral da Coxa E'), ('Glúteo (Dorso-Glúteo)', 'Glúteo (Dorso-Glúteo)'), ('Boca (Oral)', 'Boca (Oral)'), ('Outros', 'Outros')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Em Aberto'), ('ATRASADA', 'Atrasada'), ('APLICADA', 'Aplicada')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='via_administracao',
            field=models.CharField(choices=[('Intramuscular', 'Intramuscular'), ('Oral', 'Oral'), ('Subcutânea', 'Subcutânea'), ('Intradérmica', 'Intradérmica')], default='Intramuscular', max_length=50),
        ),
    ]
