# Generated by Django 6.0.1 on 2026-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_registrovacina_observacao_alter_crianca_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovacina',
            name='estrategia',
            field=models.CharField(choices=[('ROTINA', 'Rotina'), ('CAMPANHA', 'Campanha'), ('BLOQUEIO', 'Bloqueio'), ('ESPECIAL', 'Especial')], default='Rotina', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='local_aplicacao',
            field=models.CharField(blank=True, choices=[('DELTOIDE_D', 'Deltoide Direito (Braço)'), ('DELTOIDE_E', 'Deltoide Esquerdo (Braço)'), ('VASTO_LATERAL_D', 'Vasto Lateral da Coxa D'), ('VASTO_LATERAL_E', 'Vasto Lateral da Coxa E'), ('GLUTEO_D', 'Glúteo (Dorso-Glúteo)'), ('BOCA', 'Boca (Oral)'), ('OUTROS', 'Outros')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='via_administracao',
            field=models.CharField(choices=[('INTRAMUSCULAR', 'Intramuscular'), ('ORAL', 'Oral'), ('SUBCUTANEA', 'Subcutânea'), ('INTRADERMICA', 'Intradérmica')], default='Intramuscular', max_length=50),
        ),
    ]
