# Generated by Django 6.0.1 on 2026-02-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_registrovacina_estrategia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrovacina',
            options={'ordering': ['idade_alvo', 'vacina__nome']},
        ),
        migrations.AddField(
            model_name='registrovacina',
            name='idade_alvo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='estrategia',
            field=models.CharField(choices=[('ROTINA', 'Rotina'), ('CAMPANHA', 'Campanha'), ('BLOQUEIO', 'Bloqueio'), ('ESPECIAL', 'Especial')], default='ROTINA', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='via_administracao',
            field=models.CharField(choices=[('INTRAMUSCULAR', 'Intramuscular'), ('ORAL', 'Oral'), ('SUBCUTANEA', 'Subcutânea'), ('INTRADERMICA', 'Intradérmica')], default='INTRAMUSCULAR', max_length=50),
        ),
        migrations.AddIndex(
            model_name='registrovacina',
            index=models.Index(fields=['crianca'], name='core_regist_crianca_2cfb0f_idx'),
        ),
    ]
