# Generated by Django 6.0.1 on 2026-02-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_registrovacina_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotevacina',
            name='doses_por_frasco',
            field=models.PositiveBigIntegerField(default=1, help_text='Ex: 1 para dose única, 10 para frasco multidose.', verbose_name='Doses por Frasco'),
        ),
        migrations.AddField(
            model_name='lotevacina',
            name='quantidade_frascos',
            field=models.PositiveIntegerField(default=1, verbose_name='Frascos Recebidos'),
        ),
        migrations.AlterField(
            model_name='lotevacina',
            name='quantidade_disponivel',
            field=models.IntegerField(default=0, verbose_name='Doses Disponíveis'),
        ),
    ]
