# Generated by Django 6.0.1 on 2026-02-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_lotevacina_doses_por_frasco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovacina',
            name='eh_transcricao',
            field=models.BooleanField(default=False, help_text='Marque se a vacina foi aplicada em outra unidade ou data passada.', verbose_name='É Transcrição (Registro Anterior)?'),
        ),
        migrations.AddField(
            model_name='registrovacina',
            name='lote_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes_registro', to='core.lotevacina'),
        ),
    ]
