# Generated by Django 6.0.1 on 2026-02-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_registrovacina_eh_transcricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovacina',
            name='aplicado_por',
        ),
    ]
